### ISSUE TITLE
Add macOS touchbar support for YT controls

### ISSUE THREAD

**Issue by aaronleopold** [aaronleopold/music-menubar#18]
Controls should support pause, play, skip and replay functions.

**Comment by Tails128** [comment]
Reading on how to do it, interested :P

**Comment by Tails128** [comment]
@aaronleopold completed!

I am working on the icons for `rewind`, `play`, `pause`, `skip`, currently they are simply the emoji you'd use on a chat (like this: ⏭️), would you like to style it personally or should I go with the classic icons? (I still have to find them in case)

**Comment by aaronleopold** [comment]
Are you able to copy over the svgs from the player controls? They're just heroicons, but if the touchbar support requires actual icons from local files you can just whatever :)

**Comment by Tails128** [comment]
currently it seems like there is no svg support, according to [this issue](https://github.com/electron/electron/issues/9642), we could for now use `png`s from the heroicon `svg`s, but it would be super cool to centralize the svg in the future, so that in case there's any change to the svg in the application it's reflected on the touchbar without having to re-export the icons. ;)

**Comment by aaronleopold** [comment]
> it would be super cool to centralize the svg in the future, so that in case there's any change to the svg in the application it's reflected on the touchbar without having to re-export the icons. ;)

Completely agree :) You can just use whatever is easiest for now and once this app is closer to any sort of release I'd likely tidy up the UI to make sure it all matches nicely
